#!/bin/bash

NAME=AdoptOpenJDK
BASE_REPO=adoptopenjdk
VARIANTS=(browsers node node-browsers)

TAG_FILTER="grep -v -e jre"

function generate_customizations() {

  MAVEN_VERSION=$(./java_helper maven)
  ANT_VERSION=$(./java_helper ant)
  GRADLE_VERSION=$(./java_helper gradle)
  SBT_URL=$(./java_helper sbt)

  cat <<EOF

# cacerts from OpenJDK 9-slim to workaround http://bugs.java.com/view_bug.do?bug_id=8189357
# AND https://github.com/docker-library/openjdk/issues/145
#
# Created by running:
# docker run --rm openjdk:9-slim cat /etc/ssl/certs/java/cacerts | \
#   aws s3 cp - s3://circle-downloads/circleci-images/cache/linux-amd64/openjdk-9-slim-cacerts --acl public-read
RUN if java -fullversion 2>&1 | grep -q '"9.'; then \
  curl --silent --show-error --location --fail --retry 3 --output /etc/ssl/certs/java/cacerts \
       https://circle-downloads.s3.amazonaws.com/circleci-images/cache/linux-\$(dpkg --print-architecture)/openjdk-9-slim-cacerts; \
 fi

# Install Maven Version: $MAVEN_VERSION
RUN curl --silent --show-error --location --fail --retry 3 --output /tmp/apache-maven.tar.gz \
    https://www.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && curl --silent --show-error --location --fail --retry 3 --output /tmp/apache-maven.tar.gz.sha512 \
    https://www.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz.sha512 \
  && echo "\$(cat /tmp/apache-maven.tar.gz.sha512) /tmp/apache-maven.tar.gz" | sha512sum -c \
  && tar xf /tmp/apache-maven.tar.gz -C /opt/ \
  && rm /tmp/apache-maven.tar.gz /tmp/apache-maven.tar.gz.sha512 \
  && ln -s /opt/apache-maven-* /opt/apache-maven \
  && /opt/apache-maven/bin/mvn -version

# Install Ant Version: $ANT_VERSION
RUN curl --silent --show-error --location --fail --retry 3 --output /tmp/apache-ant.tar.gz \
    https://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz \
  && curl --silent --show-error --location --fail --retry 3 --output /tmp/apache-ant.tar.gz.sha512 \
    https://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz.sha512 \
  && echo "\$(cat /tmp/apache-ant.tar.gz.sha512) /tmp/apache-ant.tar.gz" | sha512sum -c \
  && tar xf /tmp/apache-ant.tar.gz -C /opt/ \
  && ln -s /opt/apache-ant-* /opt/apache-ant \
  && rm -rf /tmp/apache-ant.tar.gz /tmp/apache-ant.tar.gz.sha512 \
  && /opt/apache-ant/bin/ant -version

ENV ANT_HOME=/opt/apache-ant

# Install Gradle Version: $GRADLE_VERSION
RUN curl --silent --show-error --location --fail --retry 3 --output /tmp/gradle.zip \
    https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip \
  && curl --silent --show-error --location --fail --retry 3 --output /tmp/gradle.zip.sha256 \
    https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip.sha256 \
  && echo "\$(cat /tmp/gradle.zip.sha256) /tmp/gradle.zip" | sha256sum -c \
  && unzip -d /opt /tmp/gradle.zip \
  && rm /tmp/gradle.zip /tmp/gradle.zip.sha256 \
  && ln -s /opt/gradle-* /opt/gradle \
  && /opt/gradle/bin/gradle -version

# Install sbt from $SBT_URL
RUN curl --silent --show-error --location --fail --retry 3 --output /tmp/sbt.tgz ${SBT_URL} \
  && tar -xzf /tmp/sbt.tgz -C /opt/ \
  && rm /tmp/sbt.tgz \
  && /opt/sbt/bin/sbt -Dsbt.rootdir=true sbtVersion

# Install openjfx and build-essential
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjfx \
    && apt-get install -y build-essential \
    && rm -rf /var/lib/apt/lists/*

EOF

  # Modify path but don't inject builder path in there!
  cat <<'EOF'
# Update PATH for Java tools
ENV PATH="/opt/sbt/bin:/opt/apache-maven/bin:/opt/apache-ant/bin:/opt/gradle/bin:$PATH"

# smoke test with path
RUN mvn -version \
  && ant -version \
  && gradle -version \
  && sbt -Dsbt.rootdir=true sbtVersion

EOF
}

IMAGE_CUSTOMIZATIONS=$(generate_customizations)

source ../shared/images/generate-node.sh
source ../shared/images/generate.sh
